# Diccionario para las pistas de los caminos
diccionarioPistas =    {"Pista_1":"cruza un arroyo",
                        "Pista_2":"conduce a un pequeño poblado",
                        "Pista_3":"cruza un arroyo",
                        "Pista_4":"es un sendero tranquilo",
                        "Pista_5":"conduce a un pequeño poblado",
                        "Pista_6":"es un sendero tranquilo",
                        "Pista_7":"cruza un arroyo",
                        "Pista_8":"es un sendero tranquilo",
                        "Pista_9":"conduce a un pequeño poblado",
                        "Pista_10":"es un sendero tranquilo",
                        "Pista_11":"cruza un arroyo",
                        "Pista_12":"conduce a un pequeño poblado",
                        "Pista_13":"es un sendero tranquilo",
                        "Pista_14":"cruza un arroyo",
                        "Pista_15":"conduce a un pequeño poblado",
                        "Pista_16":"cruza un arroyo",
                        "Pista_17":"es un sendero tranquilo",
                        "Pista_18":"cruza un arroyo",
                        "Pista_19":"conduce a un pequeño poblado",
                       }