import time

# Funcion para narrar la introduccion del juego
def Introduccion():
    time.sleep(3)
    print("A fines del 2019 un virus sin identificar se empieza a propagar China y luego por el")
    time.sleep(2)
    print("mundo. El caos y la desesperación invaden a toda la humanidad, que pronto se ve")
    time.sleep(2)
    print("encerrada en cuarentena. Luego de 1 año parecía que los científicos habían desarrollado")
    time.sleep(2)
    print("una vacuna para evitar que la gente siga muriendo, todo iba bien hasta que el virus muto")
    time.sleep(2)
    print("en una cepa muy contagiosa y poco mortal, que permaneció latente por varios años.\n")
    time.sleep(3)
    print("Ya casi todos habían recuperado sus antiguas vidas, la gente empezaba a olvidar los")
    time.sleep(2)
    print("barbijos y el alcohol en gel, y fue ahí cuando, por sorpresa, muchos empezaron a morir y")
    time.sleep(2)
    print("a las pocas horas regresaban a la vida atacando a todo aquel que encuentren a su paso.\n")
    time.sleep(3)
    print("Nadie estaba preparado para algo parecido...\n")
    time.sleep(3)
    print("Las pocas personas que nunca se contagiaron no tuvieron mas remedio que huir,")
    time.sleep(2)
    print("esconderse, aislarse en lugares remotos. Mientras el mundo quedaba a merced de los")
    time.sleep(2)
    print("caminantes.\n")
    time.sleep(3)
    print("Hoy, luego de casi 2 años después, te encuentras en algún lugar de Sudamérica y te")
    time.sleep(2)
    print("persigue una horda de zombies. Trata de escapar de ellos, eligiendo caminos que te")
    time.sleep(2)
    print("lleven a un lugar seguro ¡pero cuidado! Algunos conducen a la perdición... Veamos qué")
    time.sleep(2)
    print("tan lejos puedes acompañar a sin que muera...\n")
    time.sleep(3)
    print("Frente a ti tienes 2 caminos")